{{- if eq .Values.certificates.method "cert-manager" }}
# Cert-Manager wird verwendet, um Zertifikate zu generieren
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "pod-label-mutator.fullname" . }}-cert
  labels:
    {{- include "pod-label-mutator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "pod-label-mutator.fullname" . }}-certs
  duration: {{ .Values.certificates.duration }}
  renewBefore: 720h # 30 Tage
  subject:
    organizations:
      - Kubernetes
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - {{ include "pod-label-mutator.fullname" . }}
    - {{ include "pod-label-mutator.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "pod-label-mutator.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "pod-label-mutator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certificates.certManager.issuer.kind }}
    name: {{ .Values.certificates.certManager.issuer.name }}
{{- end }}