# templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-label-mutator.fullname" . }}
  labels:
    {{- include "pod-label-mutator.labels" . | nindent 4 }}
  {{- if eq .Values.certificates.method "cert-manager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pod-label-mutator.fullname" . }}-cert
  {{- end }}
webhooks:
  - name: {{ .Values.webhook.name }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "pod-label-mutator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: {{ .Values.service.port }}
      caBundle: {{ if eq .Values.certificates.method "self-signed" }}{{ .Files.Get "certs/ca.crt" | b64enc }}{{ else }}{{ "" }}{{ end }}
    rules:
      {{- toYaml .Values.webhook.rules | nindent 6 }}
    namespaceSelector:
      {{- toYaml .Values.webhook.namespaceSelector | nindent 6 }}
    objectSelector:
      {{- toYaml .Values.webhook.objectSelector | nindent 6 }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail