# test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
    changed: "false"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
