# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-label-mutator.fullname" . }}
  labels:
    {{- include "pod-label-mutator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pod-label-mutator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pod-label-mutator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port=8443"
            - "--cert=/etc/webhook/certs/tls.crt"
            - "--key=/etc/webhook/certs/tls.key"
            - "--events-file=/var/log/webhook/events.txt"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-logs
              mountPath: /var/log/webhook
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "pod-label-mutator.fullname" . }}-certs
        - name: webhook-logs
          emptyDir: {}