# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod-label-mutator.fullname" . }}
  labels:
    {{- include "pod-label-mutator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "pod-label-mutator.selectorLabels" . | nindent 4 }}